account/urls.py
from django.urls import path
from . import views


app_name='account'
urlpatterns = [
    path('register/',views.UserRegisterView.as_view(),name='user_register'),
    path('login/',views.UserloginView.as_view(),name='user_login'),
    path('logout/',views.UserLogoutView.as_view(),name='user_logout'),
    path('profile/<int:user_id>',views.UserProfileView.as_view(),name='user_profile'),
    path('reset/',views.UserPasswordResetView.as_view(),name='reset _password'),
    path('reset/done',views.UserPasswordResetDoneView.as_view(),name='password_reset_done'),
    path('confirm/<uidb64>/<token>',views.UserPasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('confirm/complete',views.UserPasswordResetCompleteView.as_view(),name='password_reset_complete'),

    # follow and following url 
    # user id kasi ke mikhaim fallow ya unfollow konim
    path('follow/<int:user_id>',views.UserFollowView.as_view(),name='user_follow'),
    path('unfollow/<int:user_id>',views.UserUnfollowView.as_view(),name='user_unfollow'),

]

config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
    path('account/',include('account.urls',namespace='account')),
         
]

home/urls.py
from django.urls import path
from . import views

app_name='home'

urlpatterns = [
    path('',views.HomeView.as_view(),name='home'),
    path('post/<int:post_id>/<slug:post_slug>',views.PostDetailView.as_view(),name='post_detail'),
    path('post/delete/<int:post_id>',views.PostDeleteView.as_view(),name="post_delete"),
    path('post/update/<int:post_id>',views.PostUpdateView.as_view(),name='post_update'),
    path('post/create/',views.PostCreateView.as_view(),name='post_create'),
    
]

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.
class Post(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='posts')
    title=models.CharField(max_length=300,null=True)
    body=models.TextField()
    slug=models.SlugField()
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering=('-created',)

    def __str__(self) -> str:
        return self.slug
    
    def get_absolute_url(self):
        return reverse("home:post_detail", args=(self.id,self.slug))
    

class CommentModel(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='ucomments')
    post=models.ForeignKey(Post,on_delete=models.CASCADE,related_name='pcomments')
    reply=models.ForeignKey('CommentModel',on_delete=models.CASCADE,related_name='rcomments', null=True, blank=True)
    is_reply=models.BooleanField(default=False)
    body=models.TextField(max_length=500)
    created=models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'{self.user} - {self.body[:30]}'

home/views.py
from typing import Any
from django.http import HttpRequest
from django.http.response import HttpResponse as HttpResponse
from django.shortcuts import render,redirect,get_object_or_404
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.utils.text import slugify

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from .models import Post,CommentModel

from .form import PostUpdateForm,PostCreateForm,CommentCreateForm


# Create your views here.
class HomeView(View):
    def get(self,request):
        posts=Post.objects.all()
        return render(request,'home/index.html',{'posts':posts})
    

class PostDetailView(View):

    form_class=CommentCreateForm

    def get(self,request,post_id,post_slug):
        post=get_object_or_404(Post,pk=post_id,slug=post_slug) # post=Post.objects.get(pk=post_id,slug=post_slug)
        comments=post.pcomments.filter(is_reply=False) #comment asli hastan ro biyar na comment haie reply ro
        return render(request,'home/detail.html',{'post':post,'comments':comments,'form':self.form_class})

    @method_decorator(login_required)
    def post(self,request,post_id,post_slug):
            form=self.form_class(request.POST)
            post_instance=get_object_or_404(Post,pk=post_id,slug=post_slug)
            if form.is_valid():
                new_comment=form.save(commit=False)
                new_comment.user=request.user
                new_comment.post= post_instance
                new_comment.save()
                messages.success(request,'your comment submited successfully.','success')
                return redirect('home:post_detail',post_id,post_slug)



class PostDeleteView(LoginRequiredMixin,View):
    def get(self,request,post_id):
        post=get_object_or_404(Post,pk=post_id)
        # post=Post.objects.get(pk=post_id)
        if post.user.id == request.user.id:
            post.delete()
            messages.success(request,'Post successfully deleted.','success')
        else:
            messages.error(request,'you can\'t delete this post','danger')
        
        return redirect('home:home')




class PostUpdateView(View):
    
    form_class=PostUpdateForm

    def setup(self, request: HttpRequest, *args: Any, **kwargs: Any) -> None:
        self.post_instance=get_object_or_404(Post,id=kwargs['post_id'])
        # self.post_instance=Post.objects.get(id=kwargs['post_id'])
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        post=self.post_instance
        if not (request.user.id == post.user.id):
            messages.error(request,'you can\'t update this post.','danger')
            return redirect("home:home")
        return super().dispatch(request, *args, **kwargs)
    

    def get(self,request,*args, **kwargs):
        post=self.post_instance
        form=self.form_class(instance=post)
        return render (request,'home/update.html',{'form':form})

    def post(self,request,post_id,*args, **kwargs):
        post=self.post_instance
        form=self.form_class(request.POST,instance=post)
        if form.is_valid():
            new_post=form.save(commit=False)
            new_post.slug=slugify(new_post.title)
            new_post.save()
            messages.success(request,'update successfully','success')
            return redirect('home:post_detail' ,post.id,post.slug)
        

class PostCreateView(LoginRequiredMixin,View):
    form_class= PostCreateForm

    def get(self,request):
        form=self.form_class
        return render(request,'home/create.html',{'form':form})

    def post(self,request):
        form=self.form_class(request.POST)
        if form.is_valid():
            new_post=form.save(commit=False)
            new_post.user=request.user
            new_post.slug=slugify(new_post.title)
            new_post.save()
            messages.success(request,'New post created successfully','success')
            return redirect('home:post_detail',new_post.id,new_post.slug)
        

home/templates/home/create.html
{% extends "base.html" %}

{% block content %}

<h3>Create new post</h3><br>

<form method="POST" class="col-md-5">
    
    {% csrf_token %}
    {{form.as_p}}
    
    <input type="submit" Value="Create" class="btn btn-primary"></input>

</form>



{% endblock content %}

home/templates/home/detail.html
{% extends "base.html" %}


{% block content %}
    <h2>Post Detail</h2>
    <div class="card">
        <br>
        <h3>{{post.title}}</h3>
        <small>{{post.updated}}</small>
        <br>
        <small>Written by <a href="{% url "account:user_profile" post.user.id %}">{{post.user.username}}</a></small>
        <hr>
        <small>{{post.body}}</small>
        <br>
        {% if request.user.id == post.user.id %}
            <hr>
            <p>
                <a href="{% url "home:post_delete" post.id %}" class="btn btn-danger">Delete</a>
                <a href="{% url "home:post_update" post.id %}" class="btn btn-info">Update</a>
            </p>
        {% endif %}


        {% comment %} show comment form  {% endcomment %}
        <hr>
            {% if request.user.is_authenticated %}
                <form method='POST' action="" >
                    {% csrf_token %}
                    {{form.as_p}}
                    <input type="submit" value="Send" class="btn btn-primary"></input>
                </form>
            {% else %}
                <p class= "alert alert-info">Only logged in users can register comment.</p>
            {% endif %}

        {% comment %} show comment {% endcomment %}
            <hr>
            {{comments.count}} comments<br><br>
            {% for comment in comments  %}
            
                <div class="card bg-dark text-white">
                    <p class="card-header">{{comment.user}}  |  {{comment.created|timesince}} </p>
                    <p class="card-body">{{comment.body}}</p>
                </div>
            {% empty %}
            <div class="card bg-dark text-white">
                <p class="card-header">without comment </p>
            </div>
            {% endfor %}

        
        
    <div>


{% endblock content %}

home/templates/home/index.html
{% extends "base.html" %}

{% block content %}
    <h2>Posts page</h2>
    {% for post in posts  %}
        <div class="card">
            <a href="{{post.get_absolute_url}}" class="card-body"> {{post.title}} </a>
            {% comment %} <a href="{% url "home:post_detail" post.id post.slug %}" class="card-body"> {{post.title}} </a> {% endcomment %}
        </div>
    {% endfor %}
{% endblock content %}

home/templates/home/update.html
{% extends "base.html" %}


{% block content %}

    <form method="POST" action="" novalidate>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Update" class="btn btn-info"></input>
    </form>

{% endblock content %}