account/urls.py
from django.urls import path
from . import views


app_name='account'
urlpatterns = [
    path('register/',views.UserRegisterView.as_view(),name='user_register'),
    path('login/',views.UserloginView.as_view(),name='user_login'),
    path('logout/',views.UserLogoutView.as_view(),name='user_logout'),
    path('profile/<int:user_id>',views.UserProfileView.as_view(),name='user_profile'),
    path('reset/',views.UserPasswordResetView.as_view(),name='reset _password'),
    path('reset/done',views.UserPasswordResetDoneView.as_view(),name='password_reset_done'),
    path('confirm/<uidb64>/<token>',views.UserPasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('confirm/complete',views.UserPasswordResetCompleteView.as_view(),name='password_reset_complete'),

    # follow and following url 
    # user id kasi ke mikhaim fallow ya unfollow konim
    path('follow/<int:user_id>',views.UserFollowView.as_view(),name='user_follow'),
    path('unfollow/<int:user_id>',views.UserUnfollowView.as_view(),name='user_unfollow'),

]

config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
    path('account/',include('account.urls',namespace='account')),
         
]

home/urls.py
from django.urls import path
from . import views

app_name='home'

urlpatterns = [
    path('',views.HomeView.as_view(),name='home'),
    path('post/<int:post_id>/<slug:post_slug>',views.PostDetailView.as_view(),name='post_detail'),
    path('post/delete/<int:post_id>',views.PostDeleteView.as_view(),name="post_delete"),
    path('post/update/<int:post_id>',views.PostUpdateView.as_view(),name='post_update'),
    path('post/create/',views.PostCreateView.as_view(),name='post_create'),
    
]

templates/inc/messages.html
{% if messages %}

    {% for msg in messages %}
    
        <p class='alert alert-{{msg.tags}}'>{{msg}}</p>

    {% endfor %}

{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <div class="navbar-nav">
      <a class="nav-link active" href="{% url "home:home" %}">Home</a>
      {% if request.user.is_authenticated %}
      <a class="nav-link active" href="{% url "account:user_profile" request.user.pk %}">Profile</a>
      <a class="nav-link active" href="{% url "account:user_logout"  %}">Logout</a>
      {% else %} 
      <a class="nav-link active" href="{% url "account:user_register" %}">Register</a>
      <a class="nav-link active" href="{% url "account:user_login" %}">Login</a>
      {% endif %}
    </div>
  
  </div>
</nav>